# nginx conf assistent
# pip install nginx-set-conf-equitania --upgrade
# nginx-set-conf --config_path="$HOME/docker-builds/ngx-conf/"
# 13.03.2024
odoo-https:
  config_template: ngx_odoo_ssl
  ip: 
  domain: www.
  port: 11000
  cert_name: www.
  pollport: 12000
  #auth_file: authfile
Odoo only http:
  config_template: ngx_odoo_http
  ip: 
  domain: www.
  port: 11000
  pollport: 12000
  #auth_file: authfile
Fast Report:
  config_template: ngx_fast_report
  ip: 
  domain: www.
  port: 8899
  cert_name: www.
  #auth_file: authfile
Code Server:
  config_template: ngx_code_server
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
NextCloud:
  config_template: ngx_nextcloud
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
Portainer:
  config_template: ngx_portainer
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
pgAdmin:
  config_template: ngx_pgadmin
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
PWA:
  config_template: ngx_pwa
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
mailhog:
  config_template: ngx_mailhog
  ip: 
  domain: www.
  port: 
  cert_name: www.
  #auth_file: authfile
Redirect:
  config_template: ngx_redirect
  ip: 
  domain: www.
  redirect_domain: www.
  #auth_file: authfile
Redirect_SSL:
  config_template: ngx_redirect_ssl
  ip: 
  domain: www.
  cert_name: www.
  redirect_domain: www.
  #auth_file: authfile

