#!/bin/sh
if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

cp /etc/issue-standard /etc/issue
rm /etc/issue
/usr/local/bin/get-ip-address >> /etc/issue
echo "" >> /etc/issue
