version: '3'
services:
  nextcloud:
    image: "nextcloud:21.0.1-apache"
    restart: always
    volumes:
      - vol-nextcloud:/var/www/html
    ports: 
      - 127.0.0.1:8888:80
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ownerp2021
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=ownerp2021
      - NEXTCLOUD_TRUSTED_DOMAINS=*.myodoo.sh
    networks:
      - nextcloud-net
    container_name: nextcloud
  mariadb:
    image: "mariadb:focal"
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    restart: always
    volumes:
      - vol-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ownerp2021
      - MYSQL_PASSWORD=ownerp2021
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-net
    container_name: nextcloud-db  
volumes:
  vol-nextcloud:
    name: vol-nextcloud
  vol-db:
networks:
  nextcloud-net:
      driver: bridge
      name: nextcloud-net
