# Portainer
# 27.09.2024

volumes:
  vol-portainer-data:
      name: vol-portainer-data

services:
    portainer-service:
        image: portainer/portainer-ce:latest
        command: -H unix:///var/run/docker.sock
        volumes:
          - vol-portainer-data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        security_opt:
          - no-new-privileges:true  
        ports:
          - 127.0.0.1:9000:9000
        restart: always
        container_name: portainer-service
