#!/bin/bash
# deploy-nginx-base.sh — Roll out the nginx base files every vhost depends on
# Version 1.0.0 — 27.05.2026
#
# Why this exists:
#   Every vhost generated by nginx-set-conf references three shared files:
#     include nginxconfig.io/security.conf;   -> /etc/nginx/nginxconfig.io/security.conf
#     include nginxconfig.io/general.conf;    -> /etc/nginx/nginxconfig.io/general.conf
#     error_page ... /custom_50x.html; root /etc/nginx/html/;  -> /etc/nginx/html/custom_50x.html
#   If an *include* file is missing, `nginx -t` fails and the WHOLE server refuses
#   to start. This script deploys those files (versioned in scripts/nginx/) so the
#   prerequisite is never "forgotten" during a rollout.
#
# It also rolls out the main nginx.conf — but SAFELY: the old one is backed up,
# the new one is validated with `nginx -t`, and on failure the backup is rolled
# back so a bad config can never take the server down. Skip it with --no-main-conf.
#
# Idempotent: safe to re-run. Existing files are backed up before being replaced.
#
# Usage (as root or via sudo):
#   ./deploy-nginx-base.sh                 # deploy includes + html + nginx.conf
#   ./deploy-nginx-base.sh --no-main-conf  # deploy only the includes + html
#   ./deploy-nginx-base.sh --dry-run       # report only, change nothing
#   ./deploy-nginx-base.sh --src DIR       # source dir (default: repo scripts/nginx)
#   ./deploy-nginx-base.sh --dest DIR      # target dir (default: /etc/nginx)
##############################################################################

set -Eeuo pipefail

SCRIPT_VERSION="1.0.0"
SCRIPT_DATE="27.05.2026"

DEST="/etc/nginx"
SRC=""
DRY_RUN=0
WITH_MAIN_CONF=1

SEPARATOR="────────────────────────────────────────────────────────"
if [ -t 1 ]; then
    C_RED="$(printf '\033[0;31m')"; C_GREEN="$(printf '\033[0;32m')"
    C_YELLOW="$(printf '\033[1;33m')"; C_BLUE="$(printf '\033[0;34m')"; C_NC="$(printf '\033[0m')"
else
    C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_NC=""
fi

log()  { echo "${C_GREEN}$(date '+%Y-%m-%d %H:%M:%S')${C_NC} | $*"; }
warn() { echo "${C_YELLOW}$(date '+%Y-%m-%d %H:%M:%S') | WARN:${C_NC} $*" >&2; }
err()  { echo "${C_RED}$(date '+%Y-%m-%d %H:%M:%S') | ERROR:${C_NC} $*" >&2; }
die()  { err "$*"; exit 1; }
section() { echo ""; echo "${C_BLUE}${SEPARATOR}${C_NC}"; log "$*"; echo "${C_BLUE}${SEPARATOR}${C_NC}"; }

on_error() { local ec=$?; err "Aborted at line ${BASH_LINENO[0]} (exit ${ec}): ${BASH_COMMAND}"; exit "$ec"; }
trap on_error ERR

# ── Args ─────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)      DRY_RUN=1 ;;
        --no-main-conf) WITH_MAIN_CONF=0 ;;
        --src)          SRC="${2:-}"; shift ;;
        --dest)         DEST="${2:-}"; shift ;;
        --help|-h)      sed -n '2,33p' "$0"; exit 0 ;;
        *)              die "Unknown option: $1 (see --help)" ;;
    esac
    shift
done

# ── Privilege: only escalate when the target is not writable by us ───────────
# (root needs no sudo; a writable --dest, e.g. a test dir, needs none either).
SUDO=""
resolve_privilege() {
    if [ "$(id -u)" -eq 0 ]; then
        SUDO=""
        return
    fi
    local probe="$DEST"
    while [ -n "$probe" ] && [ "$probe" != "/" ] && [ ! -e "$probe" ]; do
        probe="$(dirname "$probe")"
    done
    if [ -w "$probe" ]; then
        SUDO=""
    elif command -v sudo >/dev/null 2>&1; then
        SUDO="sudo"
    else
        die "Needs root privileges to write ${DEST}, but neither root nor sudo is available."
    fi
}
resolve_privilege

# ── Locate the source directory (scripts/nginx) ──────────────
SELF_DIR="$(cd "$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")" && pwd)"
if [ -z "$SRC" ]; then
    for cand in "${SELF_DIR}/nginx" "${SELF_DIR}/../scripts/nginx" \
                "${HOME}/myodoo-docker/scripts/nginx"; do
        if [ -d "$cand" ]; then SRC="$(cd "$cand" && pwd)"; break; fi
    done
fi
[ -n "$SRC" ] && [ -d "$SRC" ] || die "Source nginx dir not found (use --src DIR)."
log "Source : ${SRC}"
log "Target : ${DEST}"
[ "$DRY_RUN" -eq 1 ] && warn "DRY-RUN — no changes will be written."

# Required source files must all be present before we touch anything.
REQUIRED=(
    "nginxconfig.io/security.conf"
    "nginxconfig.io/general.conf"
    "html/custom_50x.html"
)
for rel in "${REQUIRED[@]}"; do
    [ -f "${SRC}/${rel}" ] || die "Missing source file: ${SRC}/${rel}"
done

# ── Helpers ──────────────────────────────────────────────────
# Install a file (mode 0644), backing up an existing different copy first.
install_file() {
    local src="$1" dst="$2"
    if [ "$DRY_RUN" -eq 1 ]; then
        log "[dry-run] would install ${dst}"
        return 0
    fi
    $SUDO mkdir -p "$(dirname "$dst")"
    if [ -f "$dst" ] && ! cmp -s "$src" "$dst"; then
        local backup="${dst}.backup_$(date +%Y%m%d_%H%M%S)"
        $SUDO cp -a "$dst" "$backup"
        log "Backed up existing ${dst} -> ${backup}"
    fi
    $SUDO install -m 0644 "$src" "$dst"
    log "Installed ${dst}"
}

# ── Step 1: required includes + html (always) ────────────────
section "Deploying required vhost includes + maintenance page"
install_file "${SRC}/nginxconfig.io/security.conf" "${DEST}/nginxconfig.io/security.conf"
install_file "${SRC}/nginxconfig.io/general.conf"  "${DEST}/nginxconfig.io/general.conf"
install_file "${SRC}/html/custom_50x.html"         "${DEST}/html/custom_50x.html"

# ── Step 2: main nginx.conf (backup + validate + rollback) ───
MAIN_BACKUP=""
if [ "$WITH_MAIN_CONF" -eq 1 ] && [ -f "${SRC}/nginx.conf" ]; then
    section "Deploying main nginx.conf (with backup + validation)"
    if [ "$DRY_RUN" -eq 1 ]; then
        log "[dry-run] would back up ${DEST}/nginx.conf and install the new one."
    else
        if [ -f "${DEST}/nginx.conf" ]; then
            MAIN_BACKUP="${DEST}/nginx.conf.backup_$(date +%Y%m%d_%H%M%S)"
            $SUDO cp -a "${DEST}/nginx.conf" "$MAIN_BACKUP"
            log "Backed up ${DEST}/nginx.conf -> ${MAIN_BACKUP}"
        fi
        $SUDO install -m 0644 "${SRC}/nginx.conf" "${DEST}/nginx.conf"
        log "Installed ${DEST}/nginx.conf"
    fi
elif [ "$WITH_MAIN_CONF" -eq 1 ]; then
    warn "No nginx.conf in source — skipping main config."
else
    log "Skipping main nginx.conf (--no-main-conf)."
fi

# ── Step 3: validate with nginx -t; roll back nginx.conf on failure ──
section "Validating configuration"
if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would run 'nginx -t' and reload on success."
elif command -v nginx >/dev/null 2>&1; then
    if $SUDO nginx -t; then
        log "nginx -t passed."
        if command -v systemctl >/dev/null 2>&1; then
            if $SUDO systemctl is-active --quiet nginx; then
                $SUDO systemctl reload nginx && log "nginx reloaded."
            else
                warn "nginx is not running — not starting it here (deploy only)."
            fi
        fi
    else
        err "nginx -t FAILED after deploy."
        if [ -n "$MAIN_BACKUP" ]; then
            warn "Rolling back nginx.conf from ${MAIN_BACKUP}..."
            $SUDO cp -a "$MAIN_BACKUP" "${DEST}/nginx.conf"
            if $SUDO nginx -t; then
                err "Rolled back nginx.conf — config is valid again. Review the new nginx.conf."
            else
                err "Still invalid after rollback — the fault is NOT (only) in nginx.conf. Manual fix required."
            fi
        else
            err "No nginx.conf backup to roll back. Review the deployed includes/config manually."
        fi
        exit 1
    fi
else
    warn "nginx binary not found — skipping validation (files were deployed)."
fi

section "nginx base deploy complete"
log "Includes: ${DEST}/nginxconfig.io/{security,general}.conf"
log "Page    : ${DEST}/html/custom_50x.html"
[ "$WITH_MAIN_CONF" -eq 1 ] && log "Main    : ${DEST}/nginx.conf"
log "Run this before creating vhosts so 'include nginxconfig.io/...' never fails."
