# Docker Compose for Odoo 12
# 06.02.2021
version: '3.4'

volumes:
  vol-pg-live:
      name: vol-pg-live
  vol-odoo-live:
      name: vol-odoo-live

services:
    live-db:
        image: postgres:12.5-alpine
        environment:
          - POSTGRES_USER=ownerp
          - POSTGRES_PASSWORD=ownerp2021
          - POSTGRES_DB=postgres
        networks:
          - ownerp-net
        volumes:
          - vol-pg-live:/var/lib/postgresql/data/
        restart: always
        container_name: live-db
    live-myodoo:
        image: myodoo/myodoo-12-public:210113
        ports: 
          - 8069:8069
          - 8072:8072
        networks:
          - ownerp-net
        volumes:
          - vol-odoo-live:/opt/odoo/data
        restart: always
        container_name: live-myodoo
        command: start
networks:
    ownerp-net:
        driver: bridge
        name: ownerp-net